src/Entity/Process.php
<?php

declare(strict_types=1);

namespace App\Entity;

use DateTime;
use DateTimeInterface;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProcessRepository")
 * @ORM\Table(name="processes")
 */
class Process
{
    /**
     * Статусы процессов прогнозирования в очереди
     */
    const STATUS_WAITING = 'waiting';
    const STATUS_PROCESSING = 'processing';
    const STATUS_DONE = 'done';

    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private int $id;

    /**
     * @ORM\ManyToOne(targetEntity="Metal", inversedBy="predictions")
     */
    private Metal $metal;

    /**
     * @ORM\ManyToOne(targetEntity="Method", inversedBy="methods")
     */
    private Method $method;

    /**
     * @ORM\ManyToOne(targetEntity="Period", inversedBy="periods")
     */
    private Period $period;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private ?string $image = null;

    /**
     * @param Collection|Prediction[]
     * @ORM\OneToMany(targetEntity="Prediction", mappedBy="process")
     */
    private Collection|array $predictions;

    /**
     * @ORM\Column
     */
    private string $status;

    /**
     * @ORM\Column(type="datetime", name="created_at")
     */
    private DateTimeInterface $createdAt;

    /**
     * @ORM\Column(type="datetime", name="ended_at", nullable=true)
     */
    private ?DateTimeInterface $endedAt = null;

    /**
     * @ORM\Column(type="json")
     */
    private array $options;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private ?bool $success = null;

    public function __construct()
    {
        $this->createdAt = new DateTime();
    }

    public function getId(): int
    {
        return $this->id;
    }

    public function getMetal(): Metal
    {
        return $this->metal;
    }

    public function setMetal(Metal $metal): self
    {
        $this->metal = $metal;

        return $this;
    }

    public function getMethod(): Method
    {
        return $this->method;
    }

    public function setMethod(Method $method): self
    {
        $this->method = $method;

        return $this;
    }

    public function getPeriod(): Period
    {
        return $this->period;
    }

    public function setPeriod(Period $period): self
    {
        $this->period = $period;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    /**
     * @return Collection|Prediction[]
     */
    public function getPredictions(): Collection|array
    {
        return $this->predictions;
    }

    /**
     * @param Collection|Prediction[] $predictions
     */
    public function setPredictions(Collection|array $predictions): self
    {
        $this->predictions = $predictions;

        return $this;
    }

    public function getStatus(): string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function isStatusWaiting(): bool
    {
        return self::STATUS_WAITING === $this->status;
    }

    public function isStatusProcessing(): bool
    {
        return self::STATUS_PROCESSING === $this->status;
    }

    public function isStatusDone(): bool
    {
        return self::STATUS_DONE === $this->status;
    }

    public function getCreatedAt(): DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getEndedAt(): ?DateTimeInterface
    {
        return $this->endedAt;
    }

    public function setEndedAt(?DateTimeInterface $endedAt): Process
    {
        $this->endedAt = $endedAt;

        return $this;
    }

    public function getOptions(): array
    {
        return $this->options;
    }

    public function setOptions(array $options): self
    {
        $this->options = $options;

        return $this;
    }

    public function isSuccess(): ?bool
    {
        return $this->success;
    }

    public function setSuccess(?bool $success): self
    {
        $this->success = $success;

        return $this;
    }
}

src/Controller/ProcessController.php
<?php

declare(strict_types=1);

namespace App\Controller;

use App\Entity\Process;
use App\Annotation\Breadcrumb;
use App\Repository\ProcessRepository;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

/**
 * @Route(name="process_", path="/process/")
 */
final class ProcessController extends AbstractController
{
    const TITLE_SHOW = 'Просмотр прогноза';
    const TITLE_LIST = 'Очередь прогнозов';

    private ProcessRepository $processRepository;

    public function __construct(ProcessRepository $processRepository)
    {
        $this->processRepository = $processRepository;
    }

    /**
     * @Route(name="show", path="show/{id}", requirements={"id"="\d+"})
     * @Breadcrumb(route="method_list", name=self::TITLE_SHOW)
     */
    public function showAction(int $id): Response
    {
        $process = $this->processRepository->find($id);

        if (is_null($process)) {
            throw $this->createNotFoundException();
        }

        return $this->render('process/show.html.twig', [
            'title'   => self::TITLE_SHOW,
            'process' => $process
        ]);
    }

    /**
     * @Route(name="list", path="list")
     * @Breadcrumb(route="home", name=self::TITLE_LIST)
     */
    public function listAction(): Response
    {
        $processes = $this->processRepository->findBy([], ['id' => 'DESC']);

        return $this->render('process/list.html.twig', [
            'title'     => self::TITLE_LIST,
            'processes' => $processes
        ]);
    }

    /**
     * @Route(name="check", path="check/{id}", requirements={"id"="\d+"})
     */
    public function checkAction(int $id): JsonResponse
    {
        /** @var Process $process */
        $process = $this->processRepository->find($id);

        return $this->json(['status' => $process?->getStatus()]);
    }
}

templates/process/list.html.twig
{% extends 'base.html.twig' %}

{% block content %}
    {% if processes is empty %}
        <span>Нет данных</span>
    {% else %}
        <table class="table">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Метод</th>
                <th scope="col">Метал</th>
                <th scope="col">Тип прогноза</th>
                <th scope="col">Статус</th>
                <th scope="col">Успешно</th>
                <th scope="col">Запущено в</th>
                <th scope="col">Завершено в</th>
                <th scope="col"></th>
            </tr>
            </thead>
            <tbody>
            {% for process in processes %}
                <tr>
                    <th class="align-middle" scope="row">{{ loop.index }}</th>
                    <td class="align-middle">{{ process.method.title }}</td>
                    <td class="align-middle">{{ process.metal.title }}</td>
                    <td class="align-middle">{{ process.period.title }}</td>
                    <td class="align-middle">{{ process.status|name_status }}</td>
                    <td class="align-middle">{{ process.success ? 'Да' : 'Нет' }}</td>
                    <td class="align-middle">{{ process.createdAt|date('d.m.Y H:i') }}</td>
                    <td class="align-middle">{{ process.endedAt is null ? '-' : process.endedAt|date('d.m.Y H:i') }}</td>
                    <td class="align-middle">
                        <a href="{{ path('process_show', { id: process.id }) }}"
                           class="btn btn-primary">Подробнее</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% endif %}
{% endblock %}

templates/process/show.html.twig
{% extends 'base.html.twig' %}

{% block content %}
    {% if process.statusWaiting %}
        <h4>Прогноз находится в очереди</h4>
        {% set value = 1 %}
    {% endif %}

    {% if process.statusProcessing %}
        <h4>Прогноз запущен, необходимо подождать завершения</h4>
        {% set value = 10 %}
    {% endif %}

    {% if process.statusDone %}
        <h4>Прогноз завершен</h4>
        {% set value = 100 %}
    {% endif %}

    <div class="mb-3">
        <div>Метод: {{ process.method.title }}</div>
        <div>Метал: {{ process.metal.title }}</div>
        <div>Тип прогноза: {{ process.period.title }}</div>

        {% if process.statusDone %}
            <div>Успешно: {{ process.success ? 'Да' : 'Нет' }}</div>
        {% endif %}

        {% set options = process.options %}
        <div>Диапазон известных котировок: {{ options['start'] is null ? 'нет' : options['start']|date('d.m.Y') }} - {{ options['end'] is null ? 'нет' : options['end']|date('d.m.Y') }}</div>
        <div>Запущено в: {{ process.createdAt|date('d.m.Y H:i') }}</div>

        {% if process.endedAt is not null %}
            <div>Завершено в: {{ process.endedAt|date('d.m.Y H:i') }}</div>
        {% endif %}
    </div>

    <div class="progress" style="height: 20px">
        <div class="progress-bar progress-bar-striped progress-bar-animated"
             role="progressbar"
             aria-valuenow="{{ value }}"
             aria-valuemin="0"
             aria-valuemax="100"
             style="width: {{ value }}%"
             data-width="{{ value }}"
             data-url-check="{{ path('process_check', { id: process.id }) }}"
             data-url-redirect="{{ path('prediction_list', { show: process.id }) }}"></div>
    </div>
{% endblock %}